"""Build and use sigma-algebras on small finite sample spaces.

Variants: ``generated_sigma_algebra``, ``measurability_check``,
``sigma_of_random_variable``, ``conditional_expectation_atoms``, and
``conditional_probability_given_G``. Op-codes: ``SIGMA_GEN``, ``ATOM``,
``COUNT``, ``EVENT``, ``MEASURE_CHECK``, ``ATOM_SPLIT``, ``RV_LEVEL``,
``COND_EXP_ATOM``, ``COND_PROB_ATOM``, ``A``, ``M``, ``D``, ``CHECK``, and
``Z``. Tests independently close generator events under complements and
unions rather than trusting the emitted atom partition.
"""
import random
from fractions import Fraction

from base_generator import ProblemGenerator
from helpers import jid, step
from prob_common import prob_txt


PROBABILITY = True
VENUES = ("amber study", "birch survey", "cedar trial", "delta project",
          "ember lab", "forest audit", "granite program", "harbor test",
          "indigo review", "jade pilot", "kestrel study", "lunar trial",
          "maple project", "nova lab", "onyx survey", "pearl audit",
          "quartz program", "river test", "solar review", "topaz pilot",
          "umber study", "violet trial", "willow project", "zephyr lab")
CITIES = ("Albany", "Boston", "Cedarville", "Dover", "Erie", "Fresno",
          "Galveston", "Hartford", "Ithaca", "Juneau", "Kingston", "Lowell",
          "Madison", "Norfolk", "Olympia", "Portland", "Quincy", "Raleigh",
          "Salem", "Trenton", "Utica", "Ventura", "Wichita", "Yonkers")
NAMES = ("Aiko", "Ben", "Chidi", "Daria", "Elena", "Farah", "Gita", "Hugo",
         "Imani", "Jae", "Kira", "Luca", "Mina", "Noah", "Omar", "Priya",
         "Quinn", "Ravi", "Sofia", "Tariq", "Uma", "Vera", "Wen", "Zola")
QUERIES = {
    "generated_sigma_algebra": (
        "Find the atoms and number of events in G.",
        "Determine the partition generated by these events.",
        "Compute the finite sigma-algebra atoms and size.",
        "List the minimal nonempty events and count all their unions.",
        "Close the generators under complement and union.",
    ),
    "measurability_check": (
        "Decide whether A is G-measurable and give an atom witness.",
        "Test whether A is a union of whole atoms.",
        "Classify the event's measurability with a concrete reason.",
        "Check A against the partition induced by G.",
        "Find whether any atom is split by A.",
    ),
    "sigma_of_random_variable": (
        "Find the atoms and event count of sigma(X).",
        "Group outcomes with equal X-values to generate sigma(X).",
        "Compute the sigma-algebra induced by this random variable.",
        "Identify the level-set partition and count all unions.",
        "Determine sigma(X) from the listed finite mapping.",
    ),
    "conditional_expectation_atoms": (
        "Find E[X given G] on every atom.",
        "Average X over each G-atom under the uniform measure.",
        "Compute the atomwise conditional expectation exactly.",
        "Report the G-measurable average of X on each partition block.",
        "Evaluate and verify E[X given G].",
    ),
    "conditional_probability_given_G": (
        "Find P(A given G) on every atom.",
        "Compute the fraction of each G-atom lying in A.",
        "Evaluate this atomwise conditional probability exactly.",
        "Report E[1_A given G] on the partition blocks.",
        "Find and verify the G-conditional event probabilities.",
    ),
}


def _context():
    return (f"At the {random.choice(VENUES)} in {random.choice(CITIES)}, "
            f"{random.choice(NAMES)} studies a finite probability space.")


def _set_text(values):
    values = sorted(values)
    return "∅" if not values else "{" + ", ".join(map(str, values)) + "}"


def _partition():
    size = random.randint(4, 8)
    atom_count = random.randint(2, min(4, size))
    cuts = sorted(random.sample(range(1, size), atom_count - 1))
    boundaries = [0] + cuts + [size]
    atoms = [set(range(boundaries[index] + 1, boundaries[index + 1] + 1))
             for index in range(atom_count)]
    generators = atoms[:-1]
    return set(range(1, size + 1)), atoms, generators


def _base_problem(universe, generators, extra, target):
    generator_text = "; ".join(_set_text(event) for event in generators)
    return (f"{_context()} The uniform sample space is Omega="
            f"{_set_text(universe)}. Let G=sigma({generator_text}). {extra} "
            f"Target: {target}.").replace(".  Target", ". Target")


def _atom_steps(generators, atoms):
    steps = [step("SIGMA_GEN", "generators",
                  "; ".join(_set_text(event) for event in generators))]
    steps.extend(step("ATOM", _set_text(atom)) for atom in atoms)
    return steps


def _atoms_answer(atoms):
    return "atoms " + ", ".join(_set_text(atom) for atom in atoms)


def _sum_numbers(steps, values):
    running = values[0]
    for value in values[1:]:
        steps.append(step("A", prob_txt(running), prob_txt(value),
                          prob_txt(running + value)))
        running += value
    return running


class FiniteSigmaAlgebraGenerator(ProblemGenerator):
    """Generate exact finite sigma-algebra and conditioning exercises."""

    VARIANTS = ("generated_sigma_algebra", "measurability_check",
                "sigma_of_random_variable", "conditional_expectation_atoms",
                "conditional_probability_given_G")

    def __init__(self, variant=None):
        if variant is not None and variant not in self.VARIANTS:
            raise ValueError(f"variant must be one of {self.VARIANTS} or None")
        self.variant = variant

    @staticmethod
    def _generated():
        universe, atoms, generators = _partition()
        event_count = 2 ** len(atoms)
        problem = _base_problem(universe, generators, "",
                                "the atoms of G and its number of events")
        steps = _atom_steps(generators, atoms)
        steps.extend([
            step("COUNT", "events", f"2^{len(atoms)}", event_count),
            step("CHECK", "atoms partition Omega", _set_text(universe)),
        ])
        answer = f"{_atoms_answer(atoms)}; {event_count} events"
        return problem, steps, answer

    @staticmethod
    def _measurability():
        universe, atoms, generators = _partition()
        measurable = random.choice((True, False))
        if measurable:
            chosen = sorted(random.sample(atoms, random.randint(1, len(atoms) - 1)),
                            key=lambda atom: min(atom))
            event = set().union(*chosen)
            reason = " and ".join(_set_text(atom) for atom in chosen)
            answer = f"G-measurable; A is union of atoms {reason}"
        else:
            splittable = [atom for atom in atoms if len(atom) >= 2]
            if not splittable:
                # Rebuild until a nontrivial atom exists.
                return FiniteSigmaAlgebraGenerator._measurability()
            split_atom = random.choice(splittable)
            event = {random.choice(tuple(split_atom))}
            other_atoms = [atom for atom in atoms if atom is not split_atom]
            if other_atoms and random.choice((True, False)):
                event |= set(random.choice(other_atoms))
            answer = f"not G-measurable; A splits atom {_set_text(split_atom)}"
        extra = f"Event A={_set_text(event)}."
        problem = _base_problem(universe, generators, extra,
                                "whether A is G-measurable")
        steps = _atom_steps(generators, atoms)
        steps.append(step("EVENT", "A", _set_text(event)))
        if measurable:
            steps.append(step("MEASURE_CHECK", "A is a union of whole atoms",
                              "yes"))
        else:
            intersection = event & split_atom
            steps.extend([
                step("ATOM_SPLIT", _set_text(split_atom),
                     f"A intersection atom={_set_text(intersection)}"),
                step("MEASURE_CHECK", "A splits an atom", "no"),
            ])
        return problem, steps, answer

    @staticmethod
    def _sigma_x():
        universe, atoms, _ = _partition()
        labels = random.sample(range(-4, 8), len(atoms))
        mapping = {omega: labels[index] for index, atom in enumerate(atoms)
                   for omega in atom}
        mapping_text = ", ".join(f"{omega}:{mapping[omega]}" for omega in sorted(universe))
        problem = (f"{_context()} The uniform sample space is Omega="
                   f"{_set_text(universe)}. Random variable values by outcome are "
                   f"X={mapping_text}. Target: the atoms of sigma(X) and its "
                   f"number of events.")
        steps = []
        for label, atom in zip(labels, atoms):
            steps.extend([step("RV_LEVEL", f"X={label}", _set_text(atom)),
                          step("ATOM", _set_text(atom))])
        event_count = 2 ** len(atoms)
        steps.extend([
            step("COUNT", "events", f"2^{len(atoms)}", event_count),
            step("CHECK", "level sets partition Omega", _set_text(universe)),
        ])
        answer = f"{_atoms_answer(atoms)}; {event_count} events"
        return problem, steps, answer

    @staticmethod
    def _conditional_expectation():
        universe, atoms, generators = _partition()
        mapping = {omega: random.randint(-5, 9) for omega in universe}
        mapping_text = ", ".join(f"{omega}:{mapping[omega]}" for omega in sorted(universe))
        extra = f"Random variable values by outcome are X={mapping_text}."
        problem = _base_problem(universe, generators, extra,
                                "E[X given G] on every atom")
        steps = _atom_steps(generators, atoms)
        averages = []
        for atom in atoms:
            values = [Fraction(mapping[omega]) for omega in sorted(atom)]
            total = _sum_numbers(steps, values)
            average = total / len(atom)
            steps.extend([
                step("D", prob_txt(total), len(atom), prob_txt(average)),
                step("COND_EXP_ATOM", _set_text(atom),
                     f"sum {prob_txt(total)} / {len(atom)}", prob_txt(average)),
            ])
            averages.append(average)
        weighted = []
        for atom, average in zip(atoms, averages):
            product = len(atom) * average
            steps.append(step("M", len(atom), prob_txt(average), prob_txt(product)))
            weighted.append(product)
        weighted_sum = _sum_numbers(steps, weighted)
        conditional_mean = weighted_sum / len(universe)
        raw_sum = sum(mapping.values())
        raw_mean = Fraction(raw_sum, len(universe))
        steps.extend([
            step("D", prob_txt(weighted_sum), len(universe),
                 prob_txt(conditional_mean)),
            step("D", raw_sum, len(universe), prob_txt(raw_mean)),
            step("CHECK", "E[E[X given G]]=E[X]", prob_txt(conditional_mean),
                 prob_txt(raw_mean)),
        ])
        answer = "E[X given G] = " + "; ".join(
            f"{prob_txt(average)} on {_set_text(atom)}"
            for atom, average in zip(atoms, averages))
        return problem, steps, answer

    @staticmethod
    def _conditional_probability():
        universe, atoms, generators = _partition()
        event_size = random.randint(1, len(universe) - 1)
        event = set(random.sample(sorted(universe), event_size))
        extra = f"Event A={_set_text(event)}."
        problem = _base_problem(universe, generators, extra,
                                "P(A given G) on every atom")
        steps = _atom_steps(generators, atoms)
        probabilities, intersection_counts = [], []
        for atom in atoms:
            favorable = len(event & atom)
            probability = Fraction(favorable, len(atom))
            steps.extend([
                step("EVENT", f"A intersection {_set_text(atom)}", favorable),
                step("D", favorable, len(atom), prob_txt(probability)),
                step("COND_PROB_ATOM", _set_text(atom),
                     f"{favorable} of {len(atom)}", prob_txt(probability)),
            ])
            probabilities.append(probability)
            intersection_counts.append(Fraction(favorable))
        total_favorable = _sum_numbers(steps, intersection_counts)
        overall = total_favorable / len(universe)
        steps.extend([
            step("D", prob_txt(total_favorable), len(universe), prob_txt(overall)),
            step("CHECK", "weighted atom probabilities recover P(A)",
                 prob_txt(overall)),
        ])
        answer = "P(A given G) = " + "; ".join(
            f"{prob_txt(probability)} on {_set_text(atom)}"
            for atom, probability in zip(atoms, probabilities))
        return problem, steps, answer

    def generate(self):
        variant = self.variant or random.choice(self.VARIANTS)
        if variant == "generated_sigma_algebra":
            problem, steps, answer = self._generated()
        elif variant == "measurability_check":
            problem, steps, answer = self._measurability()
        elif variant == "sigma_of_random_variable":
            problem, steps, answer = self._sigma_x()
        elif variant == "conditional_expectation_atoms":
            problem, steps, answer = self._conditional_expectation()
        else:
            problem, steps, answer = self._conditional_probability()
        problem = f"{problem} {random.choice(QUERIES[variant])}"
        steps.append(step("Z", answer))
        return {"problem_id": jid(),
                "operation": f"probability_finite_sigma_algebra_{variant}",
                "problem": problem, "steps": steps, "final_answer": answer}
