import random
from fractions import Fraction

from base_generator import ProblemGenerator
from helpers import step, jid


COORD_LIMIT = 14
MAX_ACTIONS = 6

LATTICE_NAMES = ["L", "M", "N", "K", "L1", "L2", "Λ"]

BASIS_PHRASINGS = [
    ("Use two-dimensional LLL (Gauss reduction) on basis {basis}. "
     "Round mu to the nearest integer."),
    ("Apply Gauss lattice reduction (two-dimensional LLL) to the basis "
     "{basis}, rounding mu to the nearest integer at each size-reduction "
     "step. Give the reduced basis."),
    ("The lattice {name} is generated by the basis {basis}. Reduce that "
     "basis with the two-dimensional LLL algorithm, rounding mu to the "
     "nearest integer."),
    ("Run two-dimensional LLL by hand on the lattice basis {basis}. Round "
     "mu to the nearest integer and report the reduced basis."),
    ("A lattice {name} has basis {basis}. Use Gauss (two-dimensional LLL) "
     "reduction, rounding mu to the nearest integer, to find a reduced "
     "basis of {name}."),
]

SHORTEST_PHRASINGS = [
    ("Use two-dimensional LLL (Gauss reduction) on basis {basis} to find "
     "the shortest nonzero lattice vector. Round mu to the nearest integer "
     "and report the vector with a positive first nonzero coordinate."),
    ("The lattice {name} is generated by the basis {basis}. Reduce the "
     "basis with two-dimensional LLL, rounding mu to the nearest integer, "
     "and give the shortest nonzero vector of {name} with a positive first "
     "nonzero coordinate."),
    ("Find the shortest nonzero vector of the lattice with basis {basis} by "
     "Gauss (two-dimensional LLL) reduction. Round mu to the nearest "
     "integer and write the vector with a positive first nonzero "
     "coordinate."),
    ("Apply Gauss reduction to the lattice basis {basis}, rounding mu to "
     "the nearest integer, and report the shortest nonzero lattice vector "
     "(positive first nonzero coordinate) together with its squared "
     "length."),
    ("A lattice {name} has basis {basis}. Run two-dimensional LLL by hand, "
     "rounding mu to the nearest integer, to obtain the shortest nonzero "
     "vector of {name} with a positive first nonzero coordinate."),
]

VARIANTS = ("basis", "shortest")


def dot(u, v):
    return u[0] * v[0] + u[1] * v[1]


def sub(u, k, v):
    return (u[0] - k * v[0], u[1] - k * v[1])


def norm2(v):
    return dot(v, v)


def det2(u, v):
    return u[0] * v[1] - u[1] * v[0]


def round_fraction(fr):
    if fr >= 0:
        return (fr.numerator + fr.denominator // 2) // fr.denominator
    return -round_fraction(-fr)


def basis_text(b1, b2):
    return f"[({b1[0]},{b1[1]}),({b2[0]},{b2[1]})]"


def vec_text(v):
    return f"({v[0]},{v[1]})"


def canonical_sign(v):
    """Flip v so its first nonzero coordinate is positive."""
    if v[0] < 0 or (v[0] == 0 and v[1] < 0):
        return (-v[0], -v[1])
    return v


def gauss_reduce(b1, b2, limit=30):
    """Gauss/2-dimensional LLL reduction; returns (log, b1, b2) or None.

    The log records each loop pass so the caller can emit steps without
    re-running the algorithm.
    """
    log = []
    for _ in range(limit):
        numerator = dot(b2, b1)
        denominator = norm2(b1)
        mu = Fraction(numerator, denominator)
        k = round_fraction(mu)
        log.append(("mu", numerator, denominator, mu, k))
        if k:
            old = b2
            b2 = sub(b2, k, b1)
            log.append(("reduce", old, k, b2))
            continue
        if norm2(b2) < norm2(b1):
            log.append(("swap", norm2(b2), norm2(b1)))
            b1, b2 = b2, b1
            continue
        return log, b1, b2
    return None


def shortest_is_unique(r1, r2):
    """True when +-r1 are the only minimal-length nonzero lattice vectors.

    (r1, r2) is already reduced, so every short vector has small integer
    coordinates in that frame; a tie would make "the" shortest vector
    ambiguous for the solver.
    """
    target = norm2(r1)
    for a in range(-3, 4):
        for b in range(-3, 4):
            v = (a * r1[0] + b * r2[0], a * r1[1] + b * r2[1])
            if v == (0, 0) or v == r1 or v == (-r1[0], -r1[1]):
                continue
            if norm2(v) <= target:
                return False
    return True


def random_basis():
    """A random non-degenerate integer basis that needs real reduction work."""
    while True:
        b1 = (random.randint(-COORD_LIMIT, COORD_LIMIT),
              random.randint(-COORD_LIMIT, COORD_LIMIT))
        b2 = (random.randint(-COORD_LIMIT, COORD_LIMIT),
              random.randint(-COORD_LIMIT, COORD_LIMIT))
        if norm2(b1) == 0 or norm2(b2) == 0:
            continue
        if det2(b1, b2) == 0:
            continue
        outcome = gauss_reduce(b1, b2)
        if outcome is None:
            continue
        log, r1, r2 = outcome
        actions = sum(1 for entry in log if entry[0] in ("reduce", "swap"))
        if not 1 <= actions <= MAX_ACTIONS:
            continue
        if not shortest_is_unique(r1, r2):
            continue
        return (b1, b2), log, (r1, r2)


class LLLReductionGenerator(ProblemGenerator):
    """
    Two-dimensional LLL/Gauss lattice basis reduction on random integer
    bases, asking either for the reduced basis or for the shortest nonzero
    lattice vector.

    Op-codes used:
    - LLL_SETUP / DOT / NORM2 / MU / SIZE_REDUCE / SWAP / LLL_DONE
    - CHECK (det_invariant) / SHORTEST / NORMALIZE_SIGN
    - Z: reduced basis, or shortest vector with its squared length
    """

    def __init__(self, variant=None):
        if variant is not None and variant not in VARIANTS:
            raise ValueError(f"unknown variant: {variant}")
        self.variant = variant

    def generate(self) -> dict:
        variant = self.variant or random.choice(VARIANTS)
        (b1, b2), log, (r1, r2) = random_basis()
        original = (b1, b2)
        name = random.choice(LATTICE_NAMES)

        steps = [step("LLL_SETUP", basis_text(b1, b2))]
        for entry in log:
            if entry[0] == "mu":
                _, numerator, denominator, mu, k = entry
                steps.append(step("DOT", "b2.b1", numerator))
                steps.append(step("NORM2", "b1", denominator))
                steps.append(step("MU", str(mu), f"round={k}"))
            elif entry[0] == "reduce":
                _, old, k, new = entry
                coeff = str(k) if k >= 0 else f"({k})"
                steps.append(step("SIZE_REDUCE", f"b2={old}",
                                  f"b2-{coeff}b1={new}"))
            else:
                _, n2, n1 = entry
                steps.append(step("SWAP", f"norm b2={n2}", f"norm b1={n1}"))
        steps.append(step("LLL_DONE", basis_text(r1, r2)))

        det_before = abs(det2(*original))
        det_after = abs(det2(r1, r2))
        steps.append(step("CHECK", "det_invariant",
                          f"abs det original = {det_before}",
                          f"abs det reduced = {det_after}"))

        if variant == "shortest":
            shortest = canonical_sign(r1)
            if shortest != r1:
                steps.append(step("NORMALIZE_SIGN", vec_text(r1),
                                  vec_text(shortest)))
            steps.append(step("SHORTEST", vec_text(shortest),
                              f"norm^2={norm2(shortest)}"))
            answer = (f"shortest vector = {vec_text(shortest)}; "
                      f"norm^2 = {norm2(shortest)}")
            template = random.choice(SHORTEST_PHRASINGS)
            operation = "lll_reduction_2d_shortest"
        else:
            answer = f"reduced basis = {basis_text(r1, r2)}"
            template = random.choice(BASIS_PHRASINGS)
            operation = "lll_reduction_2d"

        problem = template.format(basis=basis_text(*original), name=name)
        steps.append(step("Z", answer))
        return dict(
            problem_id=jid(),
            operation=operation,
            problem=problem,
            steps=steps,
            final_answer=answer,
        )
